// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace DllSyringe.Net.Sys
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "DllSyringe";





        /// <summary>
        ///  Creates a new `Syringe` instance for a process identified by PID.
        ///
        ///  # Arguments
        ///  * `pid` - The PID of the target process.
        ///
        ///  # Returns
        ///  A pointer to a `Syringe` instance, or null if the process could not be opened.
        ///
        ///  # Note
        ///  The returned instance has to freed using `syringe_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "syringe_for_process", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern Syringe* syringe_for_process(uint pid);

        /// <summary>
        ///  Creates a new `Syringe` instance for a suspended process identified by PID.
        ///
        ///  # Arguments
        ///  * `pid` - The PID of the target suspended process.
        ///
        ///  # Returns
        ///  A pointer to a `Syringe` instance, or null if the process could not be opened or initialized.
        ///
        ///  # Note
        ///  The returned instance has to freed using `syringe_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "syringe_for_suspended_process", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern Syringe* syringe_for_suspended_process(uint pid);

        /// <summary>
        ///  Injects a DLL into the target process associated with the given `Syringe`.
        ///
        ///  # Arguments
        ///  * `syringe` - A pointer to the `Syringe` instance.
        ///  * `dll_path` - A C string path to the DLL to be injected.
        ///
        ///  # Returns
        ///  `true` if injection succeeded, otherwise `false`.
        ///
        ///  # Safety
        ///  The caller must ensure the given syringe pointer is valid.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "syringe_inject", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool syringe_inject(Syringe* syringe, byte* dll_path);

        /// <summary>
        ///  Finds or injects a DLL into the target process.
        ///
        ///  If the DLL is already present in the target process, it returns the existing module.
        ///  Otherwise, it injects the DLL.
        ///
        ///  # Arguments
        ///  * `syringe` - A pointer to the `Syringe` instance.
        ///  * `dll_path` - A C string path to the DLL to be injected.
        ///
        ///  # Returns
        ///  The base address of the loaded DLL or `null` if the operation failed.
        ///
        ///  # Safety
        ///  The caller must ensure that the given syringe pointer is valid.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "syringe_find_or_inject", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ModuleHandle syringe_find_or_inject(Syringe* syringe, byte* dll_path);

        /// <summary>
        ///  Ejects a module from the target process.
        ///
        ///  # Arguments
        ///  * `syringe` - A pointer to the `Syringe` instance.
        ///  * `module` - The base address of the module to be ejected.
        ///
        ///  # Returns
        ///  `true` if ejection succeeded, otherwise `false`.
        ///
        ///  # Safety
        ///  The caller must ensure that the given syringe pointer is valid and
        ///  the handle belongs to a module in the process of the syringe.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "syringe_eject", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool syringe_eject(Syringe* syringe, ModuleHandle module);

        /// <summary>
        ///  Frees a `Syringe` instance.
        ///
        ///  # Arguments
        ///  * `syringe` - A pointer to the `Syringe` instance to be freed.
        ///
        ///  # Safety
        ///  The caller must ensure that the given syringe pointer is valid or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "syringe_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void syringe_free(Syringe* syringe);


    }



}
