

#ifndef DLL_SYRINGE_H
#define DLL_SYRINGE_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * An injector that can inject modules (.dll's) into a target process.
 */
typedef struct Syringe Syringe;

/**
 * A handle to a process module.
 */
typedef void *ModuleHandle;

/**
 * Creates a new `Syringe` instance for a process identified by PID.
 *
 * # Arguments
 * * `pid` - The PID of the target process.
 *
 * # Returns
 * A pointer to a `Syringe` instance, or null if the process could not be opened.
 *
 * # Note
 * The returned instance has to freed using `syringe_free`.
 */
 struct Syringe *syringe_for_process(uint32_t pid) ;

/**
 * Creates a new `Syringe` instance for a suspended process identified by PID.
 *
 * # Arguments
 * * `pid` - The PID of the target suspended process.
 *
 * # Returns
 * A pointer to a `Syringe` instance, or null if the process could not be opened or initialized.
 *
 * # Note
 * The returned instance has to freed using `syringe_free`.
 */
 struct Syringe *syringe_for_suspended_process(uint32_t pid) ;

/**
 * Injects a DLL into the target process associated with the given `Syringe`.
 *
 * # Arguments
 * * `syringe` - A pointer to the `Syringe` instance.
 * * `dll_path` - A C string path to the DLL to be injected.
 *
 * # Returns
 * `true` if injection succeeded, otherwise `false`.
 *
 * # Safety
 * The caller must ensure the given syringe pointer is valid.
 */
 bool syringe_inject(struct Syringe *syringe, const char *dllPath) ;

/**
 * Finds or injects a DLL into the target process.
 *
 * If the DLL is already present in the target process, it returns the existing module.
 * Otherwise, it injects the DLL.
 *
 * # Arguments
 * * `syringe` - A pointer to the `Syringe` instance.
 * * `dll_path` - A C string path to the DLL to be injected.
 *
 * # Returns
 * The base address of the loaded DLL or `null` if the operation failed.
 *
 * # Safety
 * The caller must ensure that the given syringe pointer is valid.
 */
 ModuleHandle syringe_find_or_inject(struct Syringe *syringe, const char *dllPath) ;

/**
 * Ejects a module from the target process.
 *
 * # Arguments
 * * `syringe` - A pointer to the `Syringe` instance.
 * * `module` - The base address of the module to be ejected.
 *
 * # Returns
 * `true` if ejection succeeded, otherwise `false`.
 *
 * # Safety
 * The caller must ensure that the given syringe pointer is valid and
 * the handle belongs to a module in the process of the syringe.
 */
 bool syringe_eject(struct Syringe *syringe, ModuleHandle module) ;

/**
 * Frees a `Syringe` instance.
 *
 * # Arguments
 * * `syringe` - A pointer to the `Syringe` instance to be freed.
 *
 * # Safety
 * The caller must ensure that the given syringe pointer is valid or null.
 */
 void syringe_free(struct Syringe *syringe) ;

#endif  /* DLL_SYRINGE_H */


